#!/bin/bash

BROWSER_IMAGE="ghcr.io/qtvhao/k8s-ubuntu-desktop:master"
# docker pull $BROWSER_IMAGE
docker build -t $BROWSER_IMAGE .
docker run --entrypoint /bin/bash \
    -it --rm \
    --name browser-container \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e DISPLAY=$DISPLAY \
    $BROWSER_IMAGE \
    -c "Xvfb :1 -screen 0 1024x768x16 & export DISPLAY=:1 && ./loop-healthcheck"
