version: "3"
services:
  novnc:
    image: ghcr.io/qtvhao/docker-novnc:master
    restart: always
    environment:
      VNC_PASSWORD: "DNGfRiZ815CnKtoKXKSzX76zMF24x3bY"
      DISPLAY_WIDTH: 800
      DISPLAY_HEIGHT: 600
    ports:
      - 6080:8080
    networks:
      - chrome_net
  puppeteer:
    build:
      context: .
      dockerfile: Dockerfile.puppeteer
    entrypoint: bash
    command: |
      -c "set -xeo pipefail
      node ./test-chrome.js"
    depends_on:
      chrome:
        condition: service_started
    networks:
      - chrome_net
  chrome:
    stop_grace_period: 1s
    build: .
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:21223/json"]
      interval: 10s
      timeout: 10s
      retries: 5
    entrypoint: bash
    command: [
      "-c",
      "socat TCP-LISTEN:21223,reuseaddr,fork TCP:localhost:21222 & 
      ./loop-healthcheck"
    ]
    environment:
      DISPLAY: "novnc:0"
    #   PASS: "secret"
    #   UID: 1000    # Optional, default 1000
    #   GID: 1000    # Optional, default 1000
    # ports:
      # - 445:445
    # volumes:
      # - /home/example:/storage
    restart: always
    depends_on:
      novnc:
        condition: service_started
    networks:
      chrome_net:
        ipv4_address: 203.0.117.3

networks:
  chrome_net:
    ipam:
      driver: default
      config:
        - subnet: 203.0.117.0/24
  