#!/bin/bash

set -xeo pipefail

while true; do
    sleep 1
    curl -s http://localhost:21222/json | jq -e '.[] | select(.type == "page")' && break || true
done

curl -s http://localhost:21222/json | jq -e '.[] | select(.type == "page")'

while true; do
    sleep 18
    timeout 1 curl -s http://localhost:21222/json | jq .
done
